version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "01:35"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - mheob
    assignees:
      - mheob
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "01:40"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - mheob
    assignees:
      - mheob
