version: 2
updates:
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
      time: '04:45'
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    target-branch: updates/deps
    reviewers:
      - mheob
    assignees:
      - mheob
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
      time: '04:50'
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    target-branch: updates/deps
    reviewers:
      - mheob
    assignees:
      - mheob
