name: Todo to Issue

on:
  push:
    branches:
      - master

jobs:
  collectTODO:
    name: Collect TODO
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Collect TODO
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
