name: Todo to Issue

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - 'feature/**'

jobs:
  collectTODO:
    name: Collect TODO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: todo-actions
        uses: dtinth/todo-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
